name: 'RepoCreate'
description: 'Just a test for now'
inputs:
  Response:
    description: 'What to echo'
    required: true
outputs:
  github-repo-url:  
    description: 'The url of the newly created repo'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.Response }}